# training setting
train:
  num_workers: 1
  seed: 1
  train_batch_size: 1
  num_epochs: 1
  gradient_accumulation_steps: 1
  grad_checkpointing: true
  gradient_clip: 0.1
  optimizer:
    betas:
      - 0.9
      - 0.999
      - 0.9999
    eps:
      - 1.0e-30
      - 1.0e-16
    lr: 0.0001
    type: CAMEWrapper
    weight_decay: 0.0
  lr_schedule: constant
  lr_schedule_args:
    num_warmup_steps: 200
  local_save_vis: true # if save log image locally
  visualize: true
  eval_sampling_steps: 500
  log_interval: 20
  save_model_epochs: 1
  save_model_steps: 500
  work_dir: output
  online_metric: false
  eval_metric_step: 2000
  online_metric_dir: metric_helper
data:
  data_dir: [tst]
# model config
model:
  model: SanaMS_600M_P1_D28
  image_size: 512
  mixed_precision: bf16
  fp32_attention: true
  load_from:
  resume_from:
  aspect_ratio_type: ASPECT_RATIO_256
  multi_scale: true
  attn_type: linear
  linear_head_dim: 32
  ffn_type: glumbconv
  mlp_acts:
    - silu
    - silu
    - null
  mlp_ratio: 2.5
  use_pe: false
  qk_norm: false
  class_dropout_prob: 0.1
# VAE setting
vae:
  vae_type: sd3
  vae_pretrained: AuraDiffusion/16ch-vae
  scale_factor: 0.18215 #0.41407
  vae_latent_dim: 16
  vae_downsample_rate: 8
  sample_posterior: true
# text encoder
text_encoder:
  text_encoder_name: siglip
  y_norm: true
  y_norm_scale_factor: 0.01
  model_max_length: 64
# Sana schedule Flow
scheduler:
  predict_v: true
  noise_schedule: linear_flow
  pred_sigma: false
  flow_shift: 1.0
  # logit-normal timestep
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  vis_sampler: flow_euler
