data:
  data_dir: [/workspace/ae]
  image_size: 384
# training setting
train:
  num_workers: 1
  seed: 42
  train_batch_size: 16
  num_epochs: 24
  gradient_accumulation_steps: 1
  grad_checkpointing: true
  gradient_clip: 0.2
  optimizer:
    lr: 1.0e-4
    type: AdamW
    weight_decay: 0.01
    eps: 1.0e-8
    betas: [0.9, 0.999]
  lr_schedule: constant
  lr_schedule_args:
    num_warmup_steps: 0
  local_save_vis: true # if save log image locally
  visualize: true
  eval_sampling_steps: 200
  log_interval: 20
  save_model_epochs: 1
  save_model_steps: 1200
  work_dir: output
  online_metric: false
  eval_metric_step: 20000
  online_metric_dir: metric_helper
  validation_prompts:
    - portrait photo of a girl, photograph, highly detailed face, depth of field
    - Self-portrait oil painting, a beautiful cyborg woman with golden hair, 8k
    - Astronaut in a jungle, cold color palette, muted colors, detailed, 8k
    - A photo of beautiful mountain with realistic sunset and blue lake, highly detailed, masterpiece
    - This photograph captures an up-close view of a mans face and upper torso against a plain white background with visible ceiling beams. The man has light skin, short, slightly tousled dark brown hair, and a scruffy beard.man,recoilme,1boy, realistic, male focus, solo, facial hair, striped shirt, photorealistic, shirt, striped clothes, asian, looking at viewer, indoors, upper body, from below
    - woman, solo, black hair, medium length hair, female focus, solo, bedroom, messy room, standing, black tube top, black panties, camel toe , peace sign, choker, top pulled down, taking a selfie
    - a half naked woman lying on her stomach on a bed, with her head resting on her arms. She appears to be in a relaxed state, possibly sleeping or resting. A cup of coffee is placed next to her on the bed, and a book is also present nearby. The scene suggests a cozy and comfortable atmosphere, with the woman enjoying her time in bed. 1girl, solo, book, realistic, brown hair, from above, jewelry, glasses, lying, long hair, earrings, sleeping
    - The photograph captures a nude male figure with a toned physique and visible pubic hair, positioned centrally on a patterned bedspread. The subjects hands gently cradle his erect penis, which is prominently displayed in the foreground. The background features a dark room setting, emphasizing the intimate and private nature of the scene.,nsfw,male focus, 1boy, penis, testicles, solo, uncensored, bara, nude, realistic
    - A nude blonde woman with long hair and fair skin lies on her side in bed, her legs spread wide apart, revealing her genitals. She wears only a purple lace thong, and her right leg has a tattoo of a bird in blue ink. The background features a beige blanket and a window with blinds partially open, allowing natural light to filter through.,nsfw,1girl, solo, underwear, nipples, blonde hair, pussy, anus, realistic, breasts, uncensored, photorealistic, panties, ass, looking at viewer, tattoo, lying, lips, long hair, nude, on side, panty pull, barefoot, pillow, parted lips, nose, purple panties, on bed
    - A voluptuous woman with long, vibrant red hair reclines seductively on a beige couch in a modern interior. She is dressed in provocative black lingerie, featuring a lace bra and panties, accentuating her ample curves. Her legs are adorned with sheer stockings held up by garter belts, and she wears tall, glossy black high heels. A red leather belt adds a touch of contrast to her attire. The background features clean white paneling, creating a minimalist yet elegant setting that contrasts sharply with her bold, alluring presence
    - 1girl, solo, animal ears, bow, teeth, jacket, tail, open mouth, brown hair, orange background, bowtie, orange nails, simple background, cat ears, orange eyes, blue bow, animal ear fluff, cat tail, looking at viewer, upper body, shirt, school uniform, hood, striped bow, striped, white shirt, black jacket, blue bowtie, fingernails, long sleeves, cat girl, bangs, fangs, collared shirt, striped bowtie, short hair, tongue, hoodie, sharp teeth, facial mark, claw pose
    - year20,2girls,ahoge,animal ears,animal print,blonde hair,blush,bow,by boy (pixiv17542438),grabbing anothers breast,breasts,brown eyes,cleavage,closed eyes,grabbing,hair bow,kiss,kneeling,large breasts,lion (kemono friends),lion ears,lion girl,lion tail,long hair,medium hair,multiple girls,necktie,panties,shirt,shoes,siberian tiger (kemono friends),simple background,sitting,skirt,tail,thighhighs,tiger ears,tiger girl,tiger print,tiger tail,underwear,white background,yuri
    - year23,1girl,black choker,black horns,black skirt,blush,bracelet,breasts,choker,cleavage,closed mouth,collared shirt,double bun,fake horns,grey background,hair bun,halo,holding,horns,jewelry,kirara (blue archive),large breasts,long hair,looking at viewer,nail polish,necklace,panties,pantyshot,pencil skirt,pink panties,by r0 0ong,red eyes,red hair,shirt,simple background,sitting,skirt,sleeves rolled up,socks,solo,sweater,thigh strap,underwear,very long hair,white shirt,white socks
    - year21,1girl,ahoge,by amano kusatsu,armpits,arms up,bare arms,bare shoulders,bikini,blue hair,breasts,cleavage,flower,hair flower,hair ornament,heart,heart ahoge,large breasts,long hair,looking at viewer,navel,necktie,o-ring,o-ring bikini,parted lips,ponytail,solo,stomach,string bikini,swimsuit,upper body,very long hair,virtual youtuber,white bikini,yellow eyes,yukihana lamy
    - 1girl,ahoge,artist name,bent over,black thighhighs,blue sailor collar,blue skirt,blush,from behind,hair ornament,hairpin,halo,hands on own thighs,impossible hair,by kokone (coconeeeco),legs,legs apart,long sleeves,looking through own legs,natsu (blue archive),neckerchief,outdoors,panties,parted lips,pink eyes,pink hair,pink halo,pink panties,pleated skirt,red neckerchief,sailor collar,school uniform,serafuku,shirt,side ponytail,sidelocks,signature,skirt,solo,standing,striped clothes,striped panties,thick thighs,thighhighs,thighs,underwear,view between legs,white shirt
# model config
model:
  model: SanaMS_1600M_P1_D20
  image_size: 384
  aspect_ratio_type: ASPECT_RATIO_384
  mixed_precision: bf16
  fp32_attention: true
  load_from: 
  resume_from:
  multi_scale: true
  attn_type: linear
  linear_head_dim: 32
  ffn_type: glumbconv
  mlp_acts:
    - silu
    - silu
    - null
  mlp_ratio: 2.5
  use_pe: false
  qk_norm: false
  class_dropout_prob: 0.1
# VAE setting
vae:
  vae_type: sd3
  vae_pretrained: AuraDiffusion/16ch-vae
  scale_factor: 0.18215 #0.41407
  vae_latent_dim: 16
  vae_downsample_rate: 8
  sample_posterior: true
# text encoder
text_encoder:
  text_encoder_name: siglip
  y_norm: true
  y_norm_scale_factor: 0.01
  model_max_length: 64
# Sana schedule Flow
scheduler:
  predict_v: true
  noise_schedule: linear_flow
  pred_sigma: false
  flow_shift: 1.0
  # logit-normal timestep
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  vis_sampler: flow_euler
